name = "BGLR"
uuid = "7c1f0cc6-8f6f-4b7d-89fe-71fa23ac5322"
authors = ["jeffersonparil@gmail.com"]
version = "1.0.0-DEV"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Distributions = "0.25.117"
Documenter = "1.8.0"
LinearAlgebra = "1.11.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
